export enum EventEnum {
  COPY_PASSWORD = 'COPY_PASSWORD',
  OPEN_KEY = 'OPEN_KEY',
  EDIT_KEY = 'EDIT_KEY',
  DELETE_KEY = 'DELETE_KEY',
  CREATE_KEY = 'CREATE_KEY',
  REGISTER = 'REGISTER',
  LOGIN = 'LOGIN',
  SHARED_KEY = 'SHARED_KEY',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  EDIT_PROFILE = 'EDIT_PROFILE',
  LOGOUT = 'LOGOUT',
  RESET_PASSWORD = 'RESET_PASSWORD'
}
